### ISSUE TITLE
Nodeschool chapter request from kolkata, india

### ISSUE THREAD

**Issue by codetanmoy** [nodeschool/kolkata#5]
I have created an issue(https://github.com/nodeschool/discussions/issues/2111) for new node chapter at Kolkata. @riyadhalnur advised me to talk with existing chapter. Already we are associated with few open source communities like OWSAP, CSA as well as NULL. Noticed that this node school chapter is almost inactive since last year. And we are ready to takecare of this chapter becuse we are too much active and we do regular meetup on everymonth. List of our owasp meetup (https://www.owasp.org/index.php/Kolkata)

**Comment by SanketDG** [comment]
@codetanmoy hey thanks for taking interest in this. Apparently we ran into problems with the venue, and it didn't get past that.

How are you willing to proceed with this?

It would be great if the Nodeschool event is done independently of any other community.

**Comment by koustuvsinha** [comment]
Hi @codetanmoy! I was the previous coordinator of Nodeschool Kolkata and Nodeschool IEM Kolkata. I would be happy to transfer the responsibilities and repositories to you! Let me know if you are interested, we can chat in Skype (koustuv.sinha) .

**Comment by codetanmoy** [comment]
Hi, guys thanks for your feedback. @SanketDG Yes, we can do it independently. I believe collaboration might get us more participation. Hence, this is a good step.

**Comment by codetanmoy** [comment]
@koustuvsinha ok sure. my id is tanmoykhanra

**Comment by koustuvsinha** [comment]
@SanketDG I am transferring responsibilities to @codetanmoy and you. Hope you guys collaborate and make this event a success! If you need more logistical help do let me know via Skype! Many thanks!
